version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_api
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - node_api_network
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis_server
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    networks:
      - node_api_network
  # redis-commander:
  #   image: rediscommander/redis-commander:latest
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - REDIS_HOST=redis_server
  #     - REDIS_PORT=${REDIS_PORT}
  #   ports:
  #     - "8081:8081"
  #   networks:
  #     - node_api_network

networks:
  node_api_network:
    driver: bridge
